name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/platform
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/platform/helloworld

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - run: go vet ./...
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck -checks=all,-SA1019 ./...
      - run: go test ./... -race -coverprofile=coverage.out

  build-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build image
        run: docker build -t $IMAGE:${{ github.sha }} .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ github.sha }}
          exit-code: '1'
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          trivyignores: .trivyignore
      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE }}:${{ github.sha }}
      - uses: sigstore/cosign-installer@v3
      - run: docker push $IMAGE:${{ github.sha }}
      - run: cosign sign --yes $IMAGE:${{ github.sha }}
      - name: Tag and push latest
        run: |
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest
      - run: cosign sign --yes $IMAGE:latest
      - name: Checkout platform-config
        uses: actions/checkout@v4
        with:
          repository: umar11b/platform-config
          token: ${{ secrets.PLATFORM_CONFIG_PAT }}
          path: platform-config
      - name: Bump image tag
        run: |
          sed -i "s|newTag: .*|newTag: ${{ github.sha }}|" \
            platform-config/overlays/dev/helloworld/kustomization.yaml
      - name: Commit and push tag bump
        run: |
          cd platform-config
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add overlays/dev/helloworld/kustomization.yaml
          git commit -m "bump helloworld to ${{ github.sha }}"
          git push
